// Code generated by goor; DO NOT EDIT.
package examples

import (
	"io"
	"os"
	"time"
)

func NewCsv(
	name string,
	date time.Time,
	file os.File,
) *csv {
	return &csv{
		name: name,
		date: date,
		file: file,
	}
}

func (s *csv) SetName(name string) {
	s.name = name
}

func (s *csv) SetDate(date time.Time) {
	s.date = date
}

func (s *csv) SetFile(file os.File) {
	s.file = file
}

func (s *csv) SetW(w io.Writer) {
	s.w = w
}
