// Code generated by goor; DO NOT EDIT.
package examples

func NewUser(
	name string,
) *User {
	return &User{
		name: name,
	}
}

func (g *User) Id() int {
	return g.id
}

func (g *User) Age() int {
	return g.age
}

func (s *User) SetId(id int) {
	s.id = id
}

func (s *User) SetName(name string) {
	s.name = name
}
